### PR TITLE
Switch to Requests

### PR DESCRIPTION
**Pull request by GunniBusch**
I optimized your Code by removing Selenium. I implemented it by using requests. It is now more efficient. I did it by reversing the API of Bürgerbüro.

### CODE REVIEW

**Comment by sefadegirmenci** [comment]
Thanks for the contribution :)

I have one question, are you able to get data from all the offices? Ruppertstrabe seem to have a different view than the others.

**Comment by GunniBusch** [comment]
Yes. There are basically two urls. One can be used for getting data only from Ruppertstraße. There you are using this URL: `https://www22.muenchen.de/kvr/termin/index.php?cts=1064399=1`
But if you would like to get the data from the other Offices, you need to use this URL: `https://terminvereinbarung.muenchen.de/bba/termin/index.php?loc=BB`
But you the extracted Json Strings are different.
So for using both, you need to adjust only the date extraction from the JSON string.
The Ruppertstraße looks like this:
`{'LOADBALANCER': {'appoints': {'2022-08-18': [], '2022-08-19': [], '2022-08-20': [], '2022-08-21': [], '2022-08-22': [], '2022-08-23': ['15:15'], '2022-08-24': ['08:45', '08:50', '08:55', '09:00', '10:35', '10:40', '10:45', '11:10', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45'], '2022-08-25': ['08:45', '09:15', '09:30', '09:35', '09:40', '09:45', '09:50', '09:55', '10:00', '10:05', '10:10', '10:15', '10:20', '10:25', '10:30', '10:35', '10:40', '10:45', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45', '11:50', '11:55', '12:00', '12:05', '12:10', '12:15', '12:20', '12:25', '12:30', '12:35', '14:00', '14:05', '14:10', '14:15', '14:20', '14:25', '14:30', '14:35', '14:40', '14:45', '14:50', '14:55', '15:00', '15:05', '15:10', '15:15', '15:20', '15:25', '15:30', '15:35', '15:40', '15:45', '15:50', '15:55'], '2022-08-26': ['08:15', '08:20', '08:25', '08:30', '08:35', '08:40', '08:45', '08:50', '08:55', '09:00', '09:05', '09:10', '09:15', '09:20', '09:25', '09:30', '09:35', '09:40', '09:45', '09:50', '09:55', '10:00', '10:05', '10:10', '10:15', '10:20', '10:25', '10:30', '10:35', '10:40', '10:45', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45', '11:50', '11:55', '12:00', '12:05'], '2022-08-27': [], '2022-08-28': [], '2022-08-29': [], '2022-08-30': [], '2022-08-31': [], '2022-09-01': [], '2022-09-02': [], '2022-09-03': [], '2022-09-04': [], '2022-09-05': [], '2022-09-06': [], '2022-09-07': [], '2022-09-08': [], '2022-09-09': [], '2022-09-10': [], '2022-09-11': [], '2022-09-12': [], '2022-09-13': [], '2022-09-14': [], '2022-09-15': [], '2022-09-16': [], '2022-09-17': [], '2022-09-18': [], '2022-09-19': [], '2022-09-20': [], '2022-09-21': [], '2022-09-22': [], '2022-09-23': [], '2022-09-24': [], '2022-09-25': [], '2022-09-26': [], '2022-09-27': [], '2022-09-28': [], '2022-09-29': [], '2022-09-30': [], '2022-10-01': [], '2022-10-02': [], '2022-10-03': [], '2022-10-04': [], '2022-10-05': [], '2022-10-06': [], '2022-10-07': [], '2022-10-08': [], '2022-10-09': [], '2022-10-10': [], '2022-10-11': [], '2022-10-12': [], '2022-10-13': [], '2022-10-14': [], '2022-10-15': [], '2022-10-16': [], '2022-10-17': [], '2022-10-18': [], '2022-10-19': [], '2022-10-20': [], '2022-10-21': [], '2022-10-22': [], '2022-10-23': [], '2022-10-24': [], '2022-10-25': [], '2022-10-26': [], '2022-10-27': [], '2022-10-28': [], '2022-10-29': [], '2022-10-30': [], '2022-10-31': [], '2022-11-01': [], '2022-11-02': [], '2022-11-03': [], '2022-11-04': [], '2022-11-05': [], '2022-11-06': [], '2022-11-07': [], '2022-11-08': [], '2022-11-09': [], '2022-11-10': [], '2022-11-11': [], '2022-11-12': [], '2022-11-13': [], '2022-11-14': ['09:45'], '2022-11-15': ['09:30', '09:35', '10:05', '10:10', '10:15', '10:20', '10:25', '10:30', '10:35', '10:40', '10:45', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45', '11:50', '11:55', '12:00', '12:05', '12:10', '12:15', '12:20', '12:25', '12:30', '12:35', '14:00', '14:05', '14:10', '14:15', '14:20', '14:25', '14:30', '14:35', '14:40', '14:45', '14:50', '14:55', '15:00', '15:05', '15:10', '15:15', '15:20', '15:25', '15:30', '15:35', '15:40', '15:45', '15:50', '15:55', '16:00', '16:05', '16:10', '16:15', '16:20', '16:25', '16:30', '16:35', '16:40', '16:45', '16:50', '16:55', '17:00', '17:05', '17:10', '17:15']}, 'caption': 'Bürgerbüro Ruppertstraße', 'id': 'd988f171668043062a198d92af324503'}}`
And the other json like this:
`{'Termin Wartezone 1 P': {'caption': 'Bürgerbüro Pasing', 'appoints': {'2022-08-18': [], '2022-08-19': [], '2022-08-20': [], '2022-08-21': [], '2022-08-22': [], '2022-08-23': [], '2022-08-24': [], '2022-08-25': [], '2022-08-26': [], '2022-08-27': [], '2022-08-28': [], '2022-08-29': [], '2022-08-30': [], '2022-08-31': [], '2022-09-01': [], '2022-09-02': [], '2022-09-03': [], '2022-09-04': [], '2022-09-05': [], '2022-09-06': [], '2022-09-07': [], '2022-09-08': [], '2022-09-09': [], '2022-09-10': [], '2022-09-11': [], '2022-09-12': [], '2022-09-13': [], '2022-09-14': [], '2022-09-15': [], '2022-09-16': [], '2022-09-17': [], '2022-09-18': [], '2022-09-19': [], '2022-09-20': [], '2022-09-21': [], '2022-09-22': [], '2022-09-23': [], '2022-09-24': [], '2022-09-25': [], '2022-09-26': [], '2022-09-27': [], '2022-09-28': [], '2022-09-29': [], '2022-09-30': [], '2022-10-01': [], '2022-10-02': [], '2022-10-03': [], '2022-10-04': [], '2022-10-05': [], '2022-10-06': [], '2022-10-07': [], '2022-10-08': [], '2022-10-09': [], '2022-10-10': [], '2022-10-11': [], '2022-10-12': [], '2022-10-13': [], '2022-10-14': [], '2022-10-15': [], '2022-10-16': [], '2022-10-17': [], '2022-10-18': [], '2022-10-19': [], '2022-10-20': [], '2022-10-21': [], '2022-10-22': [], '2022-10-23': [], '2022-10-24': [], '2022-10-25': [], '2022-10-26': [], '2022-10-27': [], '2022-10-28': [], '2022-10-29': [], '2022-10-30': [], '2022-10-31': [], '2022-11-01': [], '2022-11-02': [], '2022-11-03': [], '2022-11-04': [], '2022-11-05': [], '2022-11-06': [], '2022-11-07': [], '2022-11-08': ['15:45'], '2022-11-09': [], '2022-11-10': [], '2022-11-11': [], '2022-11-12': [], '2022-11-13': [], '2022-11-14': [], '2022-11-15': ['10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '12:00', '12:05', '12:10', '12:15', '12:20', '12:25', '12:30', '12:35', '14:30', '14:35', '14:40', '14:45', '14:50', '14:55', '15:00', '15:05', '15:10', '15:15', '15:20', '15:25', '15:30', '15:35', '15:40', '15:45']}, 'id': '81f1b1f6253ce896116b29b9dab95519'}, 'Termin Wartezone 1 L': {'caption': 'Bürgerbüro Leonrodstraße', 'appoints': {'2022-08-18': [], '2022-08-19': [], '2022-08-20': [], '2022-08-21': [], '2022-08-22': [], '2022-08-23': [], '2022-08-24': [], '2022-08-25': [], '2022-08-26': [], '2022-08-27': [], '2022-08-28': [], '2022-08-29': [], '2022-08-30': [], '2022-08-31': [], '2022-09-01': [], '2022-09-02': [], '2022-09-03': [], '2022-09-04': [], '2022-09-05': [], '2022-09-06': [], '2022-09-07': [], '2022-09-08': [], '2022-09-09': [], '2022-09-10': [], '2022-09-11': [], '2022-09-12': [], '2022-09-13': [], '2022-09-14': [], '2022-09-15': [], '2022-09-16': [], '2022-09-17': [], '2022-09-18': [], '2022-09-19': [], '2022-09-20': [], '2022-09-21': [], '2022-09-22': [], '2022-09-23': [], '2022-09-24': [], '2022-09-25': [], '2022-09-26': [], '2022-09-27': [], '2022-09-28': [], '2022-09-29': [], '2022-09-30': [], '2022-10-01': [], '2022-10-02': [], '2022-10-03': [], '2022-10-04': [], '2022-10-05': [], '2022-10-06': [], '2022-10-07': [], '2022-10-08': [], '2022-10-09': [], '2022-10-10': [], '2022-10-11': [], '2022-10-12': [], '2022-10-13': [], '2022-10-14': [], '2022-10-15': [], '2022-10-16': [], '2022-10-17': [], '2022-10-18': [], '2022-10-19': [], '2022-10-20': [], '2022-10-21': [], '2022-10-22': [], '2022-10-23': [], '2022-10-24': [], '2022-10-25': [], '2022-10-26': [], '2022-10-27': [], '2022-10-28': [], '2022-10-29': [], '2022-10-30': [], '2022-10-31': [], '2022-11-01': [], '2022-11-02': [], '2022-11-03': [], '2022-11-04': [], '2022-11-05': [], '2022-11-06': [], '2022-11-07': [], '2022-11-08': [], '2022-11-09': [], '2022-11-10': ['11:15', '11:20', '11:25', '11:30', '14:00'], '2022-11-11': [], '2022-11-12': [], '2022-11-13': [], '2022-11-14': ['07:30', '09:45', '09:50', '09:55', '10:00', '10:05', '10:10', '10:15', '10:20', '10:25', '10:30', '10:35', '10:40', '10:45', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45', '11:50', '12:35'], '2022-11-15': ['08:30', '08:35', '08:40', '08:45', '08:50', '08:55', '09:00', '09:05', '09:10', '09:15', '09:20', '09:25', '09:30', '09:35', '09:40', '09:45', '09:50', '09:55', '10:00', '10:05', '10:10', '10:15', '10:20', '10:25', '10:30', '10:35', '10:40', '10:45', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45', '11:50', '11:55', '12:00', '12:05', '12:10', '12:15', '12:20', '12:25', '12:30', '12:35', '16:00', '16:30', '16:35', '16:40', '16:45', '16:50', '16:55', '17:00', '17:05', '17:10', '17:15', '17:20', '17:25', '17:30']}, 'id': '8276d5462af98bf4055e8269289cd394'}, 'Termin Wartezone 1 F': {'caption': 'Bürgerbüro Forstenrieder Allee', 'appoints': {'2022-08-18': [], '2022-08-19': [], '2022-08-20': [], '2022-08-21': [], '2022-08-22': [], '2022-08-23': [], '2022-08-24': [], '2022-08-25': [], '2022-08-26': [], '2022-08-27': [], '2022-08-28': [], '2022-08-29': [], '2022-08-30': [], '2022-08-31': [], '2022-09-01': [], '2022-09-02': [], '2022-09-03': [], '2022-09-04': [], '2022-09-05': [], '2022-09-06': [], '2022-09-07': [], '2022-09-08': [], '2022-09-09': [], '2022-09-10': [], '2022-09-11': [], '2022-09-12': [], '2022-09-13': [], '2022-09-14': [], '2022-09-15': [], '2022-09-16': [], '2022-09-17': [], '2022-09-18': [], '2022-09-19': [], '2022-09-20': [], '2022-09-21': [], '2022-09-22': [], '2022-09-23': [], '2022-09-24': [], '2022-09-25': [], '2022-09-26': [], '2022-09-27': [], '2022-09-28': [], '2022-09-29': [], '2022-09-30': [], '2022-10-01': [], '2022-10-02': [], '2022-10-03': [], '2022-10-04': [], '2022-10-05': [], '2022-10-06': [], '2022-10-07': [], '2022-10-08': [], '2022-10-09': [], '2022-10-10': [], '2022-10-11': [], '2022-10-12': [], '2022-10-13': [], '2022-10-14': [], '2022-10-15': [], '2022-10-16': [], '2022-10-17': [], '2022-10-18': [], '2022-10-19': [], '2022-10-20': [], '2022-10-21': [], '2022-10-22': [], '2022-10-23': [], '2022-10-24': [], '2022-10-25': [], '2022-10-26': [], '2022-10-27': [], '2022-10-28': [], '2022-10-29': [], '2022-10-30': [], '2022-10-31': [], '2022-11-01': [], '2022-11-02': [], '2022-11-03': [], '2022-11-04': [], '2022-11-05': [], '2022-11-06': [], '2022-11-07': [], '2022-11-08': [], '2022-11-09': [], '2022-11-10': ['11:50', '11:55', '12:00', '12:05'], '2022-11-11': [], '2022-11-12': [], '2022-11-13': [], '2022-11-14': [], '2022-11-15': ['09:30', '09:35', '09:40', '09:45', '10:30', '10:35', '10:40', '10:45', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45', '11:50', '11:55', '12:00', '12:05', '14:00', '14:05', '14:10', '14:15', '14:20', '14:25', '14:30', '14:35', '14:40', '14:45', '14:50', '14:55', '15:00', '15:05', '15:10', '15:15', '15:20', '15:25', '15:30', '15:35', '15:40', '15:45', '15:50', '15:55', '16:00', '16:05', '16:10', '16:15', '16:20', '16:25', '16:30', '16:35', '16:40', '16:45', '16:50', '16:55', '17:00', '17:05', '17:10', '17:15', '17:20', '17:25', '17:30']}, 'id': '468a5d6274108e3898e9457703b57523'}, 'Termin Wartezone 1 R': {'caption': 'Bürgerbüro Riesenfeldstraße', 'appoints': {'2022-08-18': [], '2022-08-19': [], '2022-08-20': [], '2022-08-21': [], '2022-08-22': [], '2022-08-23': [], '2022-08-24': [], '2022-08-25': [], '2022-08-26': [], '2022-08-27': [], '2022-08-28': [], '2022-08-29': [], '2022-08-30': [], '2022-08-31': [], '2022-09-01': [], '2022-09-02': [], '2022-09-03': [], '2022-09-04': [], '2022-09-05': [], '2022-09-06': [], '2022-09-07': [], '2022-09-08': [], '2022-09-09': [], '2022-09-10': [], '2022-09-11': [], '2022-09-12': [], '2022-09-13': [], '2022-09-14': [], '2022-09-15': [], '2022-09-16': [], '2022-09-17': [], '2022-09-18': [], '2022-09-19': [], '2022-09-20': [], '2022-09-21': [], '2022-09-22': [], '2022-09-23': [], '2022-09-24': [], '2022-09-25': [], '2022-09-26': [], '2022-09-27': [], '2022-09-28': [], '2022-09-29': [], '2022-09-30': [], '2022-10-01': [], '2022-10-02': [], '2022-10-03': [], '2022-10-04': [], '2022-10-05': [], '2022-10-06': [], '2022-10-07': [], '2022-10-08': [], '2022-10-09': [], '2022-10-10': [], '2022-10-11': [], '2022-10-12': [], '2022-10-13': [], '2022-10-14': [], '2022-10-15': [], '2022-10-16': [], '2022-10-17': [], '2022-10-18': [], '2022-10-19': [], '2022-10-20': [], '2022-10-21': [], '2022-10-22': [], '2022-10-23': [], '2022-10-24': [], '2022-10-25': [], '2022-10-26': [], '2022-10-27': [], '2022-10-28': [], '2022-10-29': [], '2022-10-30': [], '2022-10-31': [], '2022-11-01': [], '2022-11-02': [], '2022-11-03': [], '2022-11-04': [], '2022-11-05': [], '2022-11-06': [], '2022-11-07': [], '2022-11-08': [], '2022-11-09': [], '2022-11-10': ['08:45', '15:15'], '2022-11-11': [], '2022-11-12': [], '2022-11-13': [], '2022-11-14': ['09:30', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15'], '2022-11-15': ['09:00', '09:05', '09:10', '09:15', '09:20', '09:25', '09:30', '09:35', '09:40', '09:45', '09:50', '09:55', '10:00', '10:05', '10:10', '10:15', '10:20', '10:25', '10:30', '10:35', '10:40', '10:45', '10:50', '10:55', '11:00', '11:05', '11:10', '11:15', '12:00', '12:05', '12:10', '12:15', '12:20', '12:25', '12:30', '12:35', '14:00', '14:05', '14:10', '14:15', '14:20', '14:25', '14:30', '14:35', '14:40', '14:45', '14:50', '14:55', '15:00', '15:05', '15:10', '15:15', '15:20', '15:25', '15:30', '15:35', '15:40', '15:45', '15:50', '15:55', '16:00', '16:05', '16:10', '16:15', '16:45']}, 'id': '3a94cb2fc1dae9b19a13371a07c1ec03'}, 'Termin Wartezone 1 O': {'caption': 'Bürgerbüro Orleansstraße', 'appoints': {'2022-08-18': [], '2022-08-19': [], '2022-08-20': [], '2022-08-21': [], '2022-08-22': [], '2022-08-23': [], '2022-08-24': [], '2022-08-25': [], '2022-08-26': [], '2022-08-27': [], '2022-08-28': [], '2022-08-29': [], '2022-08-30': [], '2022-08-31': [], '2022-09-01': [], '2022-09-02': [], '2022-09-03': [], '2022-09-04': [], '2022-09-05': [], '2022-09-06': [], '2022-09-07': [], '2022-09-08': [], '2022-09-09': [], '2022-09-10': [], '2022-09-11': [], '2022-09-12': [], '2022-09-13': [], '2022-09-14': [], '2022-09-15': [], '2022-09-16': [], '2022-09-17': [], '2022-09-18': [], '2022-09-19': [], '2022-09-20': [], '2022-09-21': [], '2022-09-22': [], '2022-09-23': [], '2022-09-24': [], '2022-09-25': [], '2022-09-26': [], '2022-09-27': [], '2022-09-28': [], '2022-09-29': [], '2022-09-30': [], '2022-10-01': [], '2022-10-02': [], '2022-10-03': [], '2022-10-04': [], '2022-10-05': [], '2022-10-06': [], '2022-10-07': [], '2022-10-08': [], '2022-10-09': [], '2022-10-10': [], '2022-10-11': [], '2022-10-12': [], '2022-10-13': [], '2022-10-14': [], '2022-10-15': [], '2022-10-16': [], '2022-10-17': [], '2022-10-18': [], '2022-10-19': [], '2022-10-20': [], '2022-10-21': [], '2022-10-22': [], '2022-10-23': [], '2022-10-24': [], '2022-10-25': [], '2022-10-26': [], '2022-10-27': [], '2022-10-28': [], '2022-10-29': [], '2022-10-30': [], '2022-10-31': [], '2022-11-01': [], '2022-11-02': [], '2022-11-03': [], '2022-11-04': [], '2022-11-05': [], '2022-11-06': [], '2022-11-07': [], '2022-11-08': [], '2022-11-09': ['09:45'], '2022-11-10': [], '2022-11-11': [], '2022-11-12': [], '2022-11-13': [], '2022-11-14': [], '2022-11-15': ['09:35', '09:40', '09:45', '10:45', '11:15', '11:20', '11:25', '11:30', '11:35', '11:40', '11:45', '11:50', '11:55', '12:00', '12:05', '12:10', '12:15', '12:20', '12:25', '12:30', '14:00', '14:05', '14:10', '14:15', '14:20', '14:25', '14:30', '14:35', '14:40', '14:45', '14:50', '14:55', '15:00', '15:05', '15:10', '15:15', '15:20', '15:25', '15:30', '15:35', '15:40', '15:45', '15:50', '15:55', '16:00', '16:05', '17:30']}, 'id': '5e9f9bb880c291ee09f6c0499d27c73d'}}`

**Comment by sefadegirmenci** [comment]
This is great. Could you also include the second url and commit again? So that we have a fully working base in the master branch.

**Comment by GunniBusch** [comment]
I commited a version with changes regarding the other offices.
https://github.com/zaqim/Anmeldung/pull/1/commits/2938ca6b3548a237667c263991abee5c43635647

**Comment by sefadegirmenci** [comment]
Reviewed the code, everything seems fine. It's better than selenium, we can continue on this. Don't forget to star the project :)

**Pull request merged**
